[theme]
primaryColor = "#0f9b8e"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#e0e0e0"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
